{% set version = "0.3.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggside
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggside_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggside/ggside_{{ version }}.tar.gz
  sha256: d71430d88bfc2d8db912d069e20d330bf40515a89835ef2b9d3692127992a657

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    ## upper bound based on https://github.com/jtlandis/ggside/issues/56
    - r-ggplot2 >=3.4.0,<3.5
    - r-glue
    - r-gtable
    - r-rlang
    - r-scales >=1.3.0
    - r-tibble
    - r-vctrs
  run:
    - r-base
    - r-cli
    - r-ggplot2 >=3.4.0,<3.5
    - r-glue
    - r-gtable
    - r-rlang
    - r-scales >=1.3.0
    - r-tibble
    - r-vctrs

test:
  commands:
    - $R -e "library('ggside')"           # [not win]
    - "\"%R%\" -e \"library('ggside')\""  # [win]

about:
  home: https://github.com/jtlandis/ggside
  license: MIT
  summary: The grammar of graphics as shown in 'ggplot2' has provided an expressive API for users to build plots. 'ggside' extends 'ggplot2' by allowing users to add graphical information about one of the main panel's axis using a familiar 'ggplot2' style API with tidy data. This package is particularly useful for visualizing
    metadata on a discrete axis, or summary graphics on a continuous axis such as a boxplot or a density distribution.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
